In [5]:
import numpy as np

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
array=np.array([[1,2,3],[4,5,6]])

In [11]:
array[0]

array([1, 2, 3])

In [12]:
array[1]

array([4, 5, 6])

In [13]:
array[0,:2]

array([1, 2])

In [14]:
array[0,2]

3

In [15]:
array.ndim

2

In [16]:
array.shape

(2, 3)

In [17]:
array.dtype

dtype('int32')

In [18]:
array.sum()

21

In [19]:
array.min()

1

In [20]:
array.max()

6

In [21]:
array.mean()

3.5

In [22]:
array.std()

1.707825127659933

In [23]:
array[1].mean()

5.0

In [24]:
array[1].std()

0.816496580927726

In [25]:
array.var()

2.9166666666666665

In [26]:
array.std()

1.707825127659933

In [27]:
nums = np.array([1,2,2,3])

In [28]:
set(nums)

{1, 2, 3}

In [29]:
np.unique(nums)

array([1, 2, 3])

In [30]:
len(nums)

4

In [31]:
np.arange(3,8,2)

array([3, 5, 7])

In [32]:
np.where(nums==2,1,9)

array([9, 1, 1, 9])

In [33]:
nums

array([1, 2, 2, 3])

In [34]:
nums==2

array([False,  True,  True, False])

In [35]:
import pandas as pd

In [36]:
ser = pd.Series([1,2,3])

In [37]:
ser

0    1
1    2
2    3
dtype: int64

In [38]:
ser.values

array([1, 2, 3], dtype=int64)

In [39]:
print(ser.index)

RangeIndex(start=0, stop=3, step=1)


In [40]:
ser.to_numpy()

array([1, 2, 3], dtype=int64)

In [41]:
pd.Series([1,2,3],index=['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [42]:
ser.sum()

6

In [43]:
ser.min()

1

In [44]:
ser.max()

3

In [45]:
ser.mean()

2.0

In [46]:
ser.std()

1.0

In [47]:
ser.var()

1.0

In [48]:
ser.skew()

0.0

In [50]:
ser.kurt()

nan

In [51]:
ser.unique()

array([1, 2, 3], dtype=int64)

In [52]:
ser.idxmax()

2

In [53]:
ser.isin([1,2])

0     True
1     True
2    False
dtype: bool

In [54]:
ser

0    1
1    2
2    3
dtype: int64

In [55]:
ser.isin([1,2]).sum()

2

In [56]:
pd.DataFrame([[1,2,2],[3,3,4]])

0  1  2
0  1  2  2
1  3  3  4

In [82]:
df = pd.DataFrame({"aa":[1,2,3], "bb":[2,3,4]})

In [83]:
pd.DataFrame([[1,2],[3,4],[5,6]],columns=["xx","yy"])

xx  yy
0   1   2
1   3   4
2   5   6

In [84]:
pd.DataFrame(np.arange(4).reshape((2,2)),columns=["a","b"])

a  b
0  0  1
1  2  3

In [85]:
df

aa  bb
0   1   2
1   2   3
2   3   4

In [60]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [61]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [62]:
df["aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [63]:
df["aa"][:2]

0    1
1    2
Name: aa, dtype: int64

In [64]:
df

aa  bb
0   1   2
1   2   3
2   3   4

In [65]:
df.iloc[:,0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [66]:
df.loc[:,"aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [67]:
df.iloc[:2,:]

aa  bb
0   1   2
1   2   3

In [68]:
df.iloc[:,0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [69]:
df.loc[:,"aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [70]:
pd.crosstab(df["aa"], df["bb"])

bb  2  3  4
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [71]:
pd.crosstab(df["aa"], df["bb"],normalize=True)

bb         2         3         4
aa                              
1   0.333333  0.000000  0.000000
2   0.000000  0.333333  0.000000
3   0.000000  0.000000  0.333333

In [72]:
pd

<module 'pandas' from 'C:\\Users\\yuvjj\\Anaconda3\\envs\\data_science_for_python\\lib\\site-packages\\pandas\\__init__.py'>

In [73]:
df

aa  bb
0   1   2
1   2   3
2   3   4

In [74]:
df.groupby("aa")["bb"].sum()

aa
1    2
2    3
3    4
Name: bb, dtype: int64

In [75]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])