In [23]:
import pandas as pd
import os
os.environ["OMP_NUM_THREADS"] = '1'
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [60]:
df = pd.read_csv("data/iris.csv")

In [61]:
df_1 = df.head()
df_2 = df.tail(1)

In [62]:
df_1

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [63]:
df_2

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
149           5.9          3.0           5.1          1.8  virginica

In [64]:
nor_minmax = MinMaxScaler().fit(df_1.iloc[:,:-1])

In [65]:
nor_minmax

MinMaxScaler()

In [66]:
nor_minmax.transform(df_1.iloc[:,:-1])

array([[1.        , 0.83333333, 0.5       , 0.        ],
       [0.6       , 0.        , 0.5       , 0.        ],
       [0.2       , 0.33333333, 0.        , 0.        ],
       [0.        , 0.16666667, 1.        , 0.        ],
       [0.8       , 1.        , 0.5       , 0.        ]])

In [49]:
nor_minmax.transform(df_2.iloc[:,:-1])

array([[ 2.6,  0. , 19. ,  1.6]])

In [50]:
nor_minmax = MinMaxScaler().fit(df_2.iloc[:,:-1])
nor_minmax.transform(df_2.iloc[:,:-1])

array([[0., 0., 0., 0.]])

In [51]:
nor_minmax = MinMaxScaler().fit(df_1.iloc[:,:-1])
nor_minmax.transform(df_1.iloc[:,:-1])

array([[1.        , 0.83333333, 0.5       , 0.        ],
       [0.6       , 0.        , 0.5       , 0.        ],
       [0.2       , 0.33333333, 0.        , 0.        ],
       [0.        , 0.16666667, 1.        , 0.        ],
       [0.8       , 1.        , 0.5       , 0.        ]])

In [52]:
df_minmax = pd.DataFrame(nor_minmax.transform(df_1.iloc[:,:-1]),
                        columns=df_1.columns[:4])

In [53]:
df_minmax

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           1.0     0.833333           0.5          0.0
1           0.6     0.000000           0.5          0.0
2           0.2     0.333333           0.0          0.0
3           0.0     0.166667           1.0          0.0
4           0.8     1.000000           0.5          0.0

In [54]:
model = KMeans(n_clusters=3, random_state=123).fit(df.iloc[:,:-1])

C:\Users\yuvjj\Anaconda3\envs\data_science_for_python\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [55]:
model

KMeans(n_clusters=3, random_state=123)

In [56]:
model.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [57]:
model.cluster_centers_

array([[6.85      , 3.07368421, 5.74210526, 2.07105263],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

In [58]:
df["cluster"] = model.labels_
df.groupby("cluster").mean()

C:\Users\yuvjj\AppData\Local\Temp\ipykernel_16160\1415571257.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("cluster").mean()


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
cluster                                                      
0            6.850000     3.073684      5.742105     2.071053
1            5.006000     3.428000      1.462000     0.246000
2            5.901613     2.748387      4.393548     1.433871

In [59]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  cluster
0           5.1          3.5           1.4          0.2  setosa        1
1           4.9          3.0           1.4          0.2  setosa        1
2           4.7          3.2           1.3          0.2  setosa        1
3           4.6          3.1           1.5          0.2  setosa        1
4           5.0          3.6           1.4          0.2  setosa        1

In [67]:
#문제 1

In [88]:
import pandas as pd
import numpy as np

In [89]:
from sklearn.cluster import KMeans

In [90]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler


In [91]:
df = pd.read_csv("data/diabetes.csv")

In [92]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [93]:
df_non_BMI = df.loc[df["BMI"]!=0]

In [94]:
df_non_BMI_handler = KMeans(n_clusters=4,random_state=123).fit(df_non_BMI)

C:\Users\yuvjj\Anaconda3\envs\data_science_for_python\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


In [95]:
df_non_BMI_handler.labels_

array([0, 0, 0, 2, 3, 0, 2, 0, 1, 0, 0, 0, 1, 3, 0, 3, 0, 2, 2, 3, 0, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 2, 0, 0, 3, 0,
       0, 0, 0, 0, 2, 0, 0, 3, 3, 0, 3, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0,
       2, 2, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 3,
       0, 0, 2, 3, 0, 2, 2, 3, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0,
       3, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 3, 0, 3, 0, 0, 2,
       0, 2, 0, 3, 0, 0, 2, 0, 3, 0, 2, 0, 0, 3, 0, 2, 1, 0, 0, 2, 2, 2,
       2, 0, 2, 3, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 0,
       2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 2, 0, 0, 0, 3, 0, 0, 2, 3, 0, 0, 0,
       0, 3, 0, 3, 0, 2, 0, 0, 0, 0, 2, 3, 3, 2, 2, 0, 0, 1, 0, 0, 3, 2,
       0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 3, 3, 0, 0,
       1, 1, 0, 0, 0, 2, 0, 3, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 3, 0, 2, 2, 0, 0, 2, 1, 3, 0, 2, 0,
       2, 3, 3, 0, 2, 3, 3, 3, 0, 0, 2, 0, 0, 0, 2,

In [96]:
df_non_BMI_handler.cluster_centers_

array([[4.23284314e+00, 1.16642157e+02, 6.85661765e+01, 1.31372549e+01,
        4.22303922e+00, 3.15468137e+01, 4.20139706e-01, 3.48406863e+01,
        3.43137255e-01],
       [3.45833333e+00, 1.63000000e+02, 7.08333333e+01, 3.28333333e+01,
        5.09166667e+02, 3.59000000e+01, 6.07375000e-01, 3.35416667e+01,
        5.83333333e-01],
       [3.29857820e+00, 1.15004739e+02, 7.01279621e+01, 2.85308057e+01,
        1.02909953e+02, 3.24597156e+01, 4.91189573e-01, 2.99052133e+01,
        2.51184834e-01],
       [3.54385965e+00, 1.39754386e+02, 7.26666667e+01, 3.12105263e+01,
        2.24035088e+02, 3.49877193e+01, 5.96491228e-01, 3.38947368e+01,
        5.17543860e-01]])

In [97]:
df_non_BMI["cluster"] = df_non_BMI_handler.labels_

C:\Users\yuvjj\AppData\Local\Temp\ipykernel_16160\3762550341.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non_BMI["cluster"] = df_non_BMI_handler.labels_


In [105]:
df_non_BMI.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  cluster  
0                     0.627   50        1        0  
1                     0.351   31        0        0  
2                     0.672   32        1        0  
3                     0.167   21        0        2  
4                     2.288   33        1        3

In [101]:
np.unique(np.array(df_non_BMI_handler.labels_), return_counts=True)

(array([0, 1, 2, 3]), array([407,  24, 212, 114], dtype=int64))

In [104]:
df_non_BMI.groupby("cluster")[["Insulin"]].mean().reset_index()

cluster     Insulin
0        0    4.103194
1        1  509.166667
2        2  102.674528
3        3  224.035088

In [4]:
#teacher solution
import pandas as pd
from sklearn.cluster import KMeans
df = pd.read_csv("data/diabetes.csv")

In [5]:
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [6]:
df_sub = df.loc[df["BMI"]!=0,]
df_sub.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [7]:
model = KMeans(n_clusters=4, random_state=123).fit(df_sub)

C:\Users\yuvjj\Anaconda3\envs\data_science_for_python\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


In [8]:
df_sub["cluter"] = model.labels_
df_sub.head(3)

C:\Users\yuvjj\AppData\Local\Temp\ipykernel_1772\297868296.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sub["cluter"] = model.labels_


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  cluter  
0                     0.627   50        1       0  
1                     0.351   31        0       0  
2                     0.672   32        1       0

In [10]:
df_sub["cluter"].value_counts()

0    407
2    212
3    114
1     24
Name: cluter, dtype: int64

In [12]:
df_sub.groupby("cluter")["Insulin"].mean()

cluter
0      4.103194
1    509.166667
2    102.674528
3    224.035088
Name: Insulin, dtype: float64

In [108]:
#문제 2

In [135]:
df_non_BMI = df.loc[df["BMI"]!=0]

In [136]:
df_non_BMI.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [137]:
scaler_handler = MinMaxScaler().fit(df_non_BMI)

In [138]:
df_non_BMI.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [124]:
df_minmax = pd.DataFrame(scaler_handler.transform(df_non_BMI.iloc[:,:]), columns=df_non_BMI.columns)

In [125]:
df_minmax.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.314928   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.171779   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.104294   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.202454   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.509202   

   DiabetesPedigreeFunction       Age  Outcome  
0                  0.234415  0.483333      1.0  
1                  0.116567  0.166667      0.0  
2                  0.253629  0.183333      1.0  
3                  0.038002  0.000000      0.0  
4                  0.943638  0.200000      1.0

In [126]:
model = KMeans(n_clusters=4, random_state=123).fit(df_minmax)

C:\Users\yuvjj\Anaconda3\envs\data_science_for_python\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


In [127]:
model.labels_

array([2, 0, 2, 0, 1, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 1, 2, 0, 1, 0, 3, 2,
       2, 2, 2, 2, 0, 3, 3, 3, 1, 0, 3, 3, 0, 3, 2, 1, 2, 0, 3, 3, 2, 3,
       1, 0, 0, 2, 0, 0, 0, 2, 3, 0, 2, 0, 0, 0, 2, 3, 0, 2, 0, 1, 3, 0,
       0, 1, 0, 2, 0, 0, 0, 3, 0, 1, 0, 0, 3, 0, 2, 0, 3, 0, 2, 0, 0, 0,
       3, 2, 0, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0,
       2, 2, 2, 0, 0, 0, 1, 0, 0, 3, 1, 1, 0, 0, 1, 2, 1, 2, 1, 3, 0, 0,
       0, 0, 0, 0, 3, 3, 0, 2, 0, 3, 0, 3, 0, 0, 3, 2, 0, 2, 2, 0, 0, 0,
       2, 3, 3, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 3, 1, 3, 2, 3,
       0, 0, 0, 3, 2, 2, 1, 2, 1, 0, 3, 2, 2, 3, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 3, 0, 2, 2, 0, 2, 0, 0, 3, 1, 2, 2, 1, 0, 1, 2, 1, 2, 3, 3, 0,
       0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 1, 2, 1, 2, 0, 0, 0, 1, 1, 0, 2, 3,
       0, 3, 0, 3, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 3, 1, 3, 1, 0, 0,
       1, 2, 0, 3, 0, 3, 0, 2, 0, 3, 0, 1, 3, 3, 2, 2, 3, 0, 1, 0, 0, 0,
       1, 1, 1, 3, 0, 1, 0, 2, 3, 1, 1, 0, 1, 3, 0,

In [129]:
df_minmax["label"] = model.labels_

In [130]:
df_minmax.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.314928   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.171779   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.104294   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.202454   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.509202   

   DiabetesPedigreeFunction       Age  Outcome  label  
0                  0.234415  0.483333      1.0      2  
1                  0.116567  0.166667      0.0      0  
2                  0.253629  0.183333      1.0      2  
3                  0.038002  0.000000      0.0      0  
4                  0.943638  0.200000      1.0      1

In [139]:
df_minmax["label"].value_counts()

0    361
1    135
2    131
3    130
Name: label, dtype: int64

In [140]:
df_non_BMI["label"]= model.labels_

C:\Users\yuvjj\AppData\Local\Temp\ipykernel_16160\4022052026.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non_BMI["label"]= model.labels_


In [141]:
df_non_BMI.groupby("label")["Age"].mean()

label
0    25.667590
1    29.977778
2    44.297710
3    46.753846
Name: Age, dtype: float64

In [142]:
#문제 3

In [143]:
import pandas as pd

In [144]:
from sklearn.cluster import KMeans

In [145]:
from sklearn.preprocessing import MinMaxScaler

In [146]:
from sklearn.preprocessing import StandardScaler

In [147]:
df = pd.read_csv("data/diabetes.csv")

In [148]:
df_sub = df.loc[df["BMI"]!=0.]

In [149]:
df_sub.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [150]:
model = KMeans(n_clusters=3, random_state=123).fit(df_sub)

C:\Users\yuvjj\Anaconda3\envs\data_science_for_python\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


In [154]:
model.cluster_centers_[0]

array([  4.02631579, 158.44736842,  72.        ,  32.26315789,
       441.28947368,  35.10789474,   0.56921053,  34.76315789,
         0.57894737])

In [155]:
center = pd.DataFrame(model.cluster_centers_)

In [156]:
center

0           1          2          3           4          5  \
0  4.026316  158.447368  72.000000  32.263158  441.289474  35.107895   
1  3.975258  114.237113  68.647423  15.259794   14.696907  31.440619   
2  3.542735  129.376068  71.478632  30.337607  159.401709  34.134615   

          6          7         8  
0  0.569211  34.763158  0.578947  
1  0.434579  33.808247  0.301031  
2  0.535188  31.948718  0.418803

In [162]:
def uc_distnace(A,B) :
    return (((A-B)**2).sum())**(1/2)

In [163]:
uc_distnace(center.loc[0,:],center.loc[1,:])

429.24419310888464

In [164]:
uc_distnace(center.loc[0,:],center.loc[2,:])

283.405999774738

In [165]:
uc_distnace(center.loc[2,:],center.loc[1,:])

146.33847909815492